### ISSUE TITLE
请求支持snappy流式压缩

### ISSUE THREAD

**Issue by limour-blog** [sazima/proxynt#10]
感受: 使用了大佬的这个项目，感觉非常好，隐藏一下路径，挂HTTPS的网站后面，基本不会知道这是反向服务器，不会被运营商封宽带。

问题: 就是反代http时，没有压缩，家宽上行带宽小，体感不够流畅。

解决方案: 希望大佬能支持一下双向snappy流式压缩，解决带宽不足，CPU有余的痛点

snappy有现成的Python库: https://zhuanlan.zhihu.com/p/427782160

**Comment by sazima** [comment]
谢谢建议
 snappy已支持
客户端服务端都需要更新：
```
pip3 install https://github.com/sazima/proxynt/archive/refs/heads/snappy.zip
pip3 install python-snappy 
```

客户端配置：

```json
{
  "server": {
    "url": "ws://192.168.9.224:18888/websocket_path",
    "password": "helloworld",
    "compress": true
  },
  "client_name": "windows10_sql",
  "log_file": "/var/log/nt/nt.log"
}
```

**Comment by limour-blog** [comment]
感谢大佬更新！已经用上了！还发现了额外好处，显著减少了TLS in TLS特征，反代的 ssh 连接稳定了不少！
[部署过程记录](https://limour-blog.github.io/WebSocket-based-intranet-penetration-tool)
