### ISSUE TITLE
请问下，这个需要外网开放所有端口限制吗？

### ISSUE THREAD

**Issue by MilkywayVain** [sazima/proxynt#22]
大佬如题，我看了看大致流程，发现是需要配置外网服务器外网ssh端口？
但是我们的外网服务器严格限制只能暴露一个端口，是不是就没法多台同时使用了。

**Comment by sazima** [comment]
看情况， 一般需要开放一个websocket端口和多个转发用的端口。
如果转发用的端口没法开放， 你需要在外网服务器上通过127.0.0.1+端口的形式访问，服务器相当于一个跳板机。
