### ISSUE TITLE
不得不说真好用，我从2年前就开始在用，用到现在依旧想说好用

### ISSUE THREAD

**Issue by id-is-null** [sazima/proxynt#28]
不得不说真好用，我从2年前就开始在用，用到现在依旧想说好用，其他的内网穿透软件或多或少都报毒，拿这个改造一下就能实现客户端通过token映射客户端指定端口到服务器指定端口，wss随便绕过各种限制，完美适用生产环境，楼主牛批

**Comment by sazima** [comment]
👍
