### ISSUE TITLE
日志记录占用过多存储

### ISSUE THREAD

**Issue by RyanYuanSun** [sazima/proxynt#3]
连续运行客户端会生成GB级的LOG文件，占用存储空间，是否有关闭日志记录功能的方法呢？

**Comment by sazima** [comment]
> 连续运行客户端会生成GB级的LOG文件，占用存储空间，是否有关闭日志记录功能的方法呢？

后续我这边调整下日志文件数量,   现在运行的时候可以使用 '-l` 指定日志等级 , 默认是info. 可选择debug, info, warn, error, 使用warn或者error会减少很多
比如
```
nt_client -c config_c.json  -l warn
```

**Comment by RyanYuanSun** [comment]
好的，我这边尝试把日志等级更改一下，十分感谢

**Comment by sazima** [comment]
新版本限制了日志大小
