### ISSUE TITLE
使用远程桌面感觉点击鼠标有延迟，是哪里设置不对吗

### ISSUE THREAD

**Issue by nankaimy** [sazima/proxynt#31]
使用远程桌面感觉点击鼠标有延迟，是哪里设置不对吗
用其他的穿透没有延迟感

**Comment by nankaimy** [comment]
用nt_client -c config_c.json速度可以
用python run_client.py 鼠标点击会有延迟

**Comment by nankaimy** [comment]
确认不是网速问题，右键鼠标，还是有些延迟，不知道其他人有没有同样问题，还是我的设置有问题

**Comment by sazima** [comment]
git pull 最新代码尝试一下

**Comment by nankaimy** [comment]
上午测试了1.1.48 ，还有延迟感

**Comment by sazima** [comment]
> 上午测试了1.1.48 ，还有延迟感

客户端升级并重启了没。 如果还有延迟就可能是网络问题了， 我用rdp办公半天了， 感觉还行。
