### ISSUE TITLE
cpu资源占满问题

### ISSUE THREAD

**Issue by Four-D** [sazima/proxynt#5]
windows 客户端运行一天后cpu资源会被占满

**Comment by sazima** [comment]
是最新版本吗 有没有日志我看一下

--------------原始邮件--------------
发件人："Four-D ***@***.***&gt;;
发送时间：2023年8月25日(星期五) 晚上6:59
收件人："sazima/proxynt" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[sazima/proxynt] cpu资源占满问题 (Issue #5)
-----------------------------------

 

 
windows 客户端运行一天后cpu资源会被占满
